### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by banesullivan** [martinRenou/Odysis#25]
I'm unable to install this library. I've tried and tried but have no idea what's going wrong (I don't work with `npm` much)

I followed the instructions in the README: clone, pip install, then get the following errors:

```bash
$ pip install -e .
Obtaining file:///Users/bane/Documents/OpenGeoVis/Software/Odysis
    ERROR: Command errored out with exit status 1:
     command: /Users/bane/anaconda3/envs/dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/bane/Documents/OpenGeoVis/Software/Odysis/setup.py'"'"'; __file__='"'"'/Users/bane/Documents/OpenGeoVis/Software/Odysis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /Users/bane/Documents/OpenGeoVis/Software/Odysis/
    Complete output (36 lines):
    setup.py entered
    $PATH=/Users/bane/anaconda3/envs/dev/bin:/Users/bane/anaconda3/condabin:/Users/bane/.npm-global/bin:/Users/bane/anaconda3/bin:/Applications/ParaView-5.5.2.app/Contents/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/opt/X11/bin
    running egg_info
    running jsdeps
    6.7.0
    6.7.0
    Installing build dependencies with npm.  This may take a while...
    npm WARN ajv-keywords@3.3.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN odysis@0.1.0 No license field.

    audited 3412 packages in 1.83s
    found 0 vulnerabilities

    rebuilding js and css failed
    missing files: ['/Users/bane/Documents/OpenGeoVis/Software/Odysis/odysis/static/extension.js', '/Users/bane/Documents/OpenGeoVis/Software/Odysis/odysis/static/index.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/bane/Documents/OpenGeoVis/Software/Odysis/setup.py", line 179, in <module>
        setup(**setup_args)
      File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/bane/anaconda3/envs/dev/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/bane/anaconda3/envs/dev/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/bane/anaconda3/envs/dev/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/bane/Documents/OpenGeoVis/Software/Odysis/setup.py", line 45, in run
        raise e
      File "/Users/bane/Documents/OpenGeoVis/Software/Odysis/setup.py", line 38, in run
        self.distribution.run_command('jsdeps')
      File "/Users/bane/anaconda3/envs/dev/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/bane/Documents/OpenGeoVis/Software/Odysis/setup.py", line 118, in run
        raise ValueError(msg)
    ValueError: Missing file: /Users/bane/Documents/OpenGeoVis/Software/Odysis/odysis/static/extension.js
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by banesullivan** [comment]
I'd like to try out this library and make a PR to integrate #24 but I can't get started 😞

**Comment by martinRenou** [comment]
Thanks for filling this issue! Do you have `npm` installed on your machine? If not you need to install it. Then you would need to run `npm run build` from the `js` directory. Then you should try again doing the `pip install -e .`.

**Comment by banesullivan** [comment]
I didn't realize I needed to build first, thanks!
